server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    serverUrl:
#      defaultZone: http://localhost:8761/eureka

spring:
  main:
    web-application-type: reactive
  application:
    name: APIGateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: authentication-service
          uri: http://localhost:8083/
          predicates:
            - Path=/authenticate/**
          filters:
            - RewritePath=/authenticate(?<segment>/?.*), $\{segment}

        - id: chat-service
          uri: http://localhost:9001/
          predicates:
            - Path=/chat/**
          filters:
            - RewritePath=/chat(?<segment>/?.*), $\{segment}

        - id: email-service
          uri: http://localhost:8081/
          predicates:
              - Path=/email/**
          filters:
              - RewritePath=/email(?<segment>/?.*), $\{segment}

        - id: menu-service
          uri: http://localhost:8091/
          predicates:
            - Path=/menu/**
          filters:
            - RewritePath=/menu(?<segment>/?.*), $\{segment}

        - id: order-service
          uri: http://localhost:8180/
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders(?<segment>/?.*), $\{segment}

        - id: payment-service
          uri: http://localhost:9112/
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment(?<segment>/?.*), $\{segment}

        - id: registration-service
          uri: http://localhost:9090/
          predicates:
            - Path=/register/**
          filters:
            - RewritePath=/register(?<segment>/?.*), $\{segment}

        - id: table-service
          uri: http://localhost:9191/
          predicates:
            - Path=/table/**
          filters:
            - RewritePath=/table(?<segment>/?.*), $\{segment}


